<script src="<?= base_url('assets/jayvee/js/jquery-3.2.1.min.js') ?>"></script>
<script src="<?= base_url('assets/jayvee/plugins/scroll/js/wall.js') ?>"></script>
<script src="<?= base_url('assets/jayvee/js/index.js') ?>"></script>
<script src="<?= base_url('assets/jayvee/js/highlight.min.js') ?>"></script>
<script src="<?= base_url('assets/jayvee/plugins/bootstrap/js/popper.min.js') ?>"></script>
<script src="<?= base_url('assets/jayvee/plugins/bootstrap/js/bootstrap.min.js') ?>"></script>
<script src="<?= base_url('assets/jayvee/js/menu-toggle.js') ?>"></script>
<script src="<?= base_url('assets/jayvee/plugins/progress/jquery.lineProgressbar.js') ?>"></script>
<script src="<?= base_url('assets/jayvee/js/line-progress.js') ?>"></script>
<script src="<?= base_url('assets/jayvee/plugins/cubeportfolio/js/jquery.cubeportfolio.min.js') ?>"></script>
<script src="<?= base_url('assets/jayvee/plugins/cubeportfolio/js/cube-awesome-work.js') ?>"></script>
<script src="<?= base_url('assets/jayvee/js/cube-portfolio.js') ?>"></script>